user_xpath = "//input[@type='text' and @placeholder='Enter your active Email ID / Username']"
pwd_xpath = "//input[@type='password']"
login_button_xpath = "//button[contains(text(),'Login')]"
user_name_edit_icon_xpath = "//div[@class='hdn']//em[contains(@class, 'edit')]"
first_name_input_xpath = "//input[@id='name']"
save_button_xpath = "//button[@id='saveBasicDetailsBtn']"
