name: Daily Trigger at 8:50 AM on leaf-1

on:
  schedule:
    - cron: '50 8 * * *'  # Runs daily at 8:50 AM UTC
  workflow_dispatch:  # Enables manual trigger in GitHub UI
  push:
    branches:
      - feature_hari-v1

jobs:
  run-code:
    if: github.ref == 'refs/heads/feature_hari-v1'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest
